server:
  port: 9091

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:9092/eureka

logging:
  level:
    com.netflix.eureka: OFF
    com.netflix.discovery: OFF